version: "3.8"
services:
  backend:
    build: ./node-hello
    expose:
      - "3000"
    networks:
      - todo-net

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - todo-net

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
